---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(p8105.datasets)
library(dplyr)
library(rnoaa)
library(httr)
library(jsonlite)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
data(rest_inspec)

plot3 = rest_inspec |>
  select(boro, cuisine_description, grade, score) |>
  filter(grade == "C") |>
  plot_ly(x = ~boro, y = ~score, color = ~cuisine_description, type = "box", colors = "viridis") 

plot3
```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
df2 = read_csv("nynoaadat/nynoaadat.csv") |>
    mutate(date = format(date, format = "%Y%m%d")) |>
  select(id, date, tmin, prcp) |>
  drop_na(tmin) |>
  filter(tmin < -300)

plot2 = df2 |>
  plot_ly(x = ~tmin, y = ~date, color = ~tmin,
    type = "scatter", mode = "markers", alpha = 0.5)

plot2
```

### Chart C

```{r}
data(instacart)

plot1 = instacart |>
  count(department) |>
  mutate(department = fct_reorder(department, n, .desc = TRUE)) |>
  plot_ly(x = ~department, y = ~n, color = ~department,
          type = "bar", colors = "viridis")

plot1
```

